# Netlify Configuration for SvelteKit

[build]
  command = "npm run build:netlify"
  publish = "ui/build"

[build.environment]
  NODE_VERSION = "20"

# SvelteKit adapter handles routing automatically
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 