# Netlify Configuration for Translation Helps API + UI

[build]
  functions = "netlify/functions"
  publish = "ui/build"
  command = "npm run build:all"

[build.environment]
  NODE_VERSION = "18"

# Redirect /api/* to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Handle SvelteKit routing - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CORS headers for API endpoints
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "public, max-age=300"

# Function-specific configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 