/**
 * Generated by scripts/sync-version.js
 * SINGLE SOURCE OF TRUTH for server version. Do not edit manually.
 */

export const VERSION = "7.19.6";

export function getVersion(): string {
  return VERSION;
}

export function resetVersionCache(): void {
  // no-op in generated version file
}
